Repository adamperkowski/highlightos, pull requests merged in 2024-07, with the labels that each got.

#1 Upgrade README #1 - build instructions
  README.md
Labels: documentation

#2 Upgrade README 2 - instructions
  README.md
Labels: documentation

#6 Implement interrupts, serial, keyboard input and commands added previously
  shell/.cargo/config.toml
  shell/Cargo.toml
  shell/TODO
  shell/src/allocator.rs
  shell/src/allocator/bump.rs
  shell/src/allocator/fixed_size_block.rs
  shell/src/allocator/linked_list.rs
  shell/src/cmd/mod.rs
  shell/src/gdt.rs
  shell/src/interrupts.rs
  shell/src/keyboard_buffer.rs
  shell/src/lib.rs
  shell/src/main.rs
  shell/src/mem.rs
  shell/src/serial.rs
  shell/src/shell.rs
  shell/src/vga_buffer.rs
Labels: developement

#13 Fixed `chcolor` freezing when provided incorrect values
  shell/src/cmd/mod.rs
Labels: bug

#15 Bump spin, uart_16550 & *.*.x
  shell/Cargo.toml
Labels: deps

#14 Added colors for specific events
  README.md
  shell/TODO
  shell/src/cmd/mod.rs
  shell/src/interrupts.rs
  shell/src/main.rs
  shell/src/vga_buffer.rs
Labels: enhancement, developement

#16 Update README.md
  README.md
Labels: documentation

#19 Add backspace and command interrupting functionality
  README.md
  shell/src/interrupts.rs
  shell/src/vga_buffer.rs
Labels: enhancement, developement

#21 Document the assembly code & fix formatting in README
  README.md
  asm/boot.asm
Labels: documentation
